name: GomokuMC
main: org.us._42.laphicet.gomoku.minecraft.GomokuMC
version: 0.0.1
author: apuel & mlu
api-version: 1.13

commands:
  startgame:
    description: To start game
    usage: /startgame
    permission: gomoku.startgame
    permission-message: You don't have access to this command!
